version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "umt"
s3_bucket = "@AWS_S3_ARTIFACTS_BUCKET"
s3_prefix = "umt"
region = "@AWS_DEFAULT_REGION"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
