version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "umt"
s3_bucket = "arzov-umatch-artifacts-dev"
s3_prefix = "umt"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
