Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Backend para Arzov Umatch

Globals:
  Function:
    MemorySize: 256
    Timeout: 180
    Handler: index.handler
    Runtime: nodejs12.x
    Layers:
      - arn:aws:lambda:us-east-2:223453650380:layer:umt:1

Resources:
  UMTAddCourt:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: umt-add-court
      CodeUri: lambda/functions/umt-add-court/
      Role: arn:aws:iam::223453650380:role/arv-lambda