Transform: AWS::Serverless-2016-10-31
Description: >
  Backend en AWS

Globals:
  Function:
    MemorySize: 256
    Timeout: 180
    Handler: index.handler
    Runtime: nodejs12.x
    Layers:
      - @LAMBDA_LAYER

Resources:
  # ==================================
  # AWS Lambda
  # ==================================
  UMTAddCourt:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: umt-add-court
      CodeUri: lambda/functions/umt-add-court/
      Role: @LAMBDA_ROLE
    
  # ==================================
  # AWS DynamoDB
  # ==================================
  UMTCourts:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "hashKey"
          AttributeType: "N"
        - AttributeName: "rangeKey"
          AttributeType: "S"
        - AttributeName: "geohash"
          AttributeType: "N"
      BillingMode: "PAY_PER_REQUEST"
      GlobalSecondaryIndexes:
        - IndexName: "rangeKey-index"
          KeySchema:
            - AttributeName: "rangeKey"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      KeySchema:
        - AttributeName: "hashKey"
          KeyType: "HASH"
        - AttributeName: "rangeKey"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - IndexName: "geohash-index"
          KeySchema:
            - AttributeName: "hashKey"
              KeyType: "HASH"
            - AttributeName: "geohash"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      TableName: "UMT_COURTS"