
  S3BucketUMTPWA:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: @AWS_S3_PWA_BUCKET
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true      
