
  ASResolverUMTGetMessages:
    Type: AWS::AppSync::Resolver
    Properties: 
      ApiId: !GetAtt ASGraphQLApiUMT.ApiId
      DataSourceName: !GetAtt ASDataSourceUMTDBMessages.Name
      FieldName: getMessages
      RequestMappingTemplate: >
        {
          "version" : "2017-02-28",
          "operation" : "Query",
          "query" : {
              "expression": "hashKey = :v1",
              "expressionValues" : {
                  ":v1" : {
                      "S" : "$ctx.args.hashKey"
                  }
              }
          },
          "limit": 20,
          "scanIndexForward": false,
          "nextToken": $util.toJson($util.defaultIfNullOrBlank($ctx.args.nextToken, null))
        }
      ResponseMappingTemplate: >
        $util.toJson($ctx.result)
      TypeName: Query